-- +goose Up

INSERT INTO COMPANY (NAME, ADDRESS, REMOVED, CREATED, UPDATED) VALUES
  ('COMPANY_1', 'UNKNOWN_1', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
  ('COMPANY_2', 'UNKNOWN_2', TRUE , CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- +goose Down

