-- +goose Up
CREATE TABLE COMPANY (
  ID BIGSERIAL PRIMARY KEY,
  NAME TEXT NOT NULL,
  ADDRESS TEXT NOT NULL,
  REMOVED BOOL NOT NULL DEFAULT FALSE,
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED TIMESTAMP
);

CREATE UNIQUE INDEX IDX_COMPANY_UID ON COMPANY(ID);

CREATE TYPE COMPANY_EVENT_TYPE AS ENUM ('CREATED', 'UPDATED', 'REMOVED');
CREATE TYPE COMPANY_EVENT_STATUS AS ENUM ('LOCK', 'UNLOCK');

CREATE TABLE COMPANY_EVENTS (
  ID BIGSERIAL PRIMARY KEY,
  COMPANY_ID BIGSERIAL NOT NULL,
  TYPE COMPANY_EVENT_TYPE NOT NULL,
  STATUS COMPANY_EVENT_STATUS NOT NULL,
  PAYLOAD JSONB,
  UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IDX_COMPANY_EVENTS_UID ON COMPANY_EVENTS(ID);
CREATE INDEX IDX_COMPANY_EVENTS_COMP_ID ON COMPANY_EVENTS(COMPANY_ID);

-- +goose Down
DROP INDEX IDX_COMPANY_UID;

DROP TABLE COMPANY;

DROP TYPE COMPANY_EVENT_TYPE;
DROP TYPE COMPANY_EVENT_STATUS;

DROP INDEX IDX_COMPANY_EVENTS_UID;
DROP INDEX IDX_COMPANY_EVENTS_COMP_ID;

DROP TABLE COMPANY_EVENTS;
