// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package bss_company_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BsscompanyApiServiceClient is the client API for BsscompanyApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BsscompanyApiServiceClient interface {
	// DescribecompanyV1 - Describe a company
	DescribecompanyV1(ctx context.Context, in *DescribecompanyV1Request, opts ...grpc.CallOption) (*DescribecompanyV1Response, error)
}

type bsscompanyApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBsscompanyApiServiceClient(cc grpc.ClientConnInterface) BsscompanyApiServiceClient {
	return &bsscompanyApiServiceClient{cc}
}

func (c *bsscompanyApiServiceClient) DescribecompanyV1(ctx context.Context, in *DescribecompanyV1Request, opts ...grpc.CallOption) (*DescribecompanyV1Response, error) {
	out := new(DescribecompanyV1Response)
	err := c.cc.Invoke(ctx, "/ozonmp.bss_company_api.v1.bsscompanyApiService/DescribecompanyV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BsscompanyApiServiceServer is the server API for BsscompanyApiService service.
// All implementations must embed UnimplementedBsscompanyApiServiceServer
// for forward compatibility
type BsscompanyApiServiceServer interface {
	// DescribecompanyV1 - Describe a company
	DescribecompanyV1(context.Context, *DescribecompanyV1Request) (*DescribecompanyV1Response, error)
	mustEmbedUnimplementedBsscompanyApiServiceServer()
}

// UnimplementedBsscompanyApiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBsscompanyApiServiceServer struct {
}

func (UnimplementedBsscompanyApiServiceServer) DescribecompanyV1(context.Context, *DescribecompanyV1Request) (*DescribecompanyV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribecompanyV1 not implemented")
}
func (UnimplementedBsscompanyApiServiceServer) mustEmbedUnimplementedBsscompanyApiServiceServer() {}

// UnsafeBsscompanyApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BsscompanyApiServiceServer will
// result in compilation errors.
type UnsafeBsscompanyApiServiceServer interface {
	mustEmbedUnimplementedBsscompanyApiServiceServer()
}

func RegisterBsscompanyApiServiceServer(s grpc.ServiceRegistrar, srv BsscompanyApiServiceServer) {
	s.RegisterService(&BsscompanyApiService_ServiceDesc, srv)
}

func _BsscompanyApiService_DescribecompanyV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribecompanyV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BsscompanyApiServiceServer).DescribecompanyV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozonmp.bss_company_api.v1.bsscompanyApiService/DescribecompanyV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BsscompanyApiServiceServer).DescribecompanyV1(ctx, req.(*DescribecompanyV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// BsscompanyApiService_ServiceDesc is the grpc.ServiceDesc for BsscompanyApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BsscompanyApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ozonmp.bss_company_api.v1.bsscompanyApiService",
	HandlerType: (*BsscompanyApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribecompanyV1",
			Handler:    _BsscompanyApiService_DescribecompanyV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ozonmp/bss_company_api/v1/bss_company_api.proto",
}
